//this code is generated by python script, you should not edit it.
//author: fengxp
//email: xiaopeifenng AT hotmail.com
//copyright: happynetwork


#include "test_db.h"
#include <assert.h>
#include <string.h>

samples_insert_test_res_t samples_insert_test(DBProxyClient* client, const char* f1, int f2, const char* f3, const char* f4, int f5)
{
  char sql[1024] = {0};
  char dbname[50] = "test";
  sprintf(sql,"insert into student values ('%s', %d, '%s', '%s', %d)", f1, f2, f3, f4, f5);
  result_t res = client->db_query(dbname, sql);
  samples_insert_test_res_t r;
  r.code = res.code;
  memcpy(r.desc, res.desc.c_str(), res.desc.length());
  return r;
}

void samples_insert_test_async(DBProxyClient* client, const char* f1, int f2, const char* f3, const char* f4, int f5, query_call_cb_t func, void* arg)
{
  char sql[1024] = {0};
  char dbname[50] = "test";
  sprintf(sql, "insert into student values ('%s', %d, '%s', '%s', %d)", f1, f2, f3, f4, f5);
  client->db_async_query(dbname, sql, func, arg);
}

samples_update_test_res_t samples_update_test(DBProxyClient* client, const char* f1)
{
  char sql[1024] = {0};
  char dbname[50] = "test";
  sprintf(sql,"update student set name = '%s' where id = 1", f1);
  result_t res = client->db_query(dbname, sql);
  samples_update_test_res_t r;
  r.code = res.code;
  memcpy(r.desc, res.desc.c_str(), res.desc.length());
  return r;
}

void samples_update_test_async(DBProxyClient* client, const char* f1, query_call_cb_t func, void* arg)
{
  char sql[1024] = {0};
  char dbname[50] = "test";
  sprintf(sql, "update student set name = '%s' where id = 1", f1);
  client->db_async_query(dbname, sql, func, arg);
}

samples_select_test_res_t samples_select_test(DBProxyClient* client, int f1)
{
  char sql[1024] = {0};
  char dbname[50] = "test";
  sprintf(sql,"select name, age, address, school from student where id = %d", f1);
  result_t res = client->db_query(dbname, sql);
  samples_select_test_res_t r;
  r.code = res.code;
  memcpy(r.desc, res.desc.c_str(), res.desc.length());
  r.rows_count = res.getRowCount();

  if( r.rows_count > 0 ){
    r.rows = new samples_select_test_field_t[r.rows_count];
    bool b;
    for(int i = 0; i < r.rows_count; ++i){
      b = res.getRowDataAsStr(i, 0, r.rows[i].name);
      assert(b);
      b = res.getRowDataAsInt(i, 1, r.rows[i].age);
      assert(b);
      b = res.getRowDataAsStr(i, 2, r.rows[i].address);
      assert(b);
      b = res.getRowDataAsStr(i, 3, r.rows[i].school);
      assert(b);
    }
  }
  return r;
}

void samples_select_test_async(DBProxyClient* client, int f1, query_call_cb_t func, void* arg)
{
  char sql[1024] = {0};
  char dbname[50] = "test";
  sprintf(sql, "select name, age, address, school from student where id = %d", f1);
  client->db_async_query(dbname, sql, func, arg);
}

