//this code is generated by python script, you should not edit it.
//author: fengxp
//email: xiaopeifenng AT hotmail.com
//copyright: happynetwork


#ifndef SAMPLES_SQL_H
#define SAMPLES_SQL_H
#include "DBProxyClient.h"

extern "C"{

typedef struct samples_insert_test_res{
  int code;
  char desc[1024];
}samples_insert_test_res_t;

samples_insert_test_res_t samples_insert_test(DBProxyClient* client, const char* f1, int f2, const char* f3, const char* f4, int f5);
void samples_insert_test_async(DBProxyClient* client, const char* f1, int f2, const char* f3, const char* f4, int f5, query_call_cb_t func, void* arg);

typedef struct samples_update_test_res{
  int code;
  char desc[1024];
}samples_update_test_res_t;

samples_update_test_res_t samples_update_test(DBProxyClient* client, const char* f1);
void samples_update_test_async(DBProxyClient* client, const char* f1, query_call_cb_t func, void* arg);

typedef struct samples_select_test_field{
  char name[1024];
  int age;
  char address[1024];
  char school[1024];
}samples_select_test_field_t;

typedef struct samples_select_test_res{
	samples_select_test_res()
	{
		memset(desc, 0, sizeof(desc));
	}

  int code;
  char desc[1024];
  int rows_count;
  samples_select_test_field_t* rows;
}samples_select_test_res_t;

samples_select_test_res_t samples_select_test(DBProxyClient* client, int f1);
void samples_select_test_async(DBProxyClient* client, int f1, query_call_cb_t func, void* arg);


}
#endif
